version: '3'
services:
  db:
    image: postgres:9.6.18
    volumes:
      - ./tmp/database:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
    labels:
        com.datadoghq.ad.logs: '[{"source": "trubya-rails_db_1", "service": "database"}]'
    
     
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
        - DD_TRACE_ANALYTICS_ENABLED=true
    labels:
        com.datadoghq.ad.logs: '[{"source": "trubya-rails_web_1", "service": "webapp"}]'

networks:   
    default:
        external:
            name: datadog_network