version: '3'
services:
  db:
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
    environment:
      RAILS_ENV: development
volumes:
  gem_cache:
  db_data:
  node_modules: